#!/bin/bash

ZSHENV_LINE="source /etc/zsh/local-config"
ZSHENV_PATH="/etc/zsh/zshenv"

echo $*
case "$1" in
    configure)
        echo "Updating neovim remote plugins..."
        vim --headless -c ":UpdateRemotePlugins" -c ":TSInstall" -c ":q"
        echo "Ensure sourcing local-config file during zsh startup..."
        grep -qxF "$ZSHENV_LINE" $ZSHENV_PATH || echo "$ZSHENV_LINE" >> $ZSHENV_PATH
        ;;
    *)
        echo "Unknown postinst command: $1"
esac
