[system]
binaries = "/"
neovim = "/"
misc = "/"


[local]
"binaries/usr/bin" = "~/.local/bin"
"binaries/usr/local/share/zsh/site-functions" = "~/.local/zsh/site-functions"
"binaries/usr/share/man/man1" = "~/.local/man"
"neovim/etc/xdg/nvim" = "~/.config/nvim"
"misc/etc/gitconfig" = "~/.config/gitconfig"
"misc/etc/tmux.conf" = "~/.tmux.conf"
"misc/usr/share/tmux/dracula" = "~/.local/tmux/dracula"
"zsh/usr/share/zsh/config" = "~/.local/zsh/config"
