[system]
binaries = "/"
nvim = "/etc/xdg/nvim"
zsh = "/usr/share/zsh/config"
"misc/gitconfig" = "/etc/gitconfig"
"misc/tmux.conf" = "/etc/tmux.conf"
"misc/dracula" = "/usr/share/tmux/dracula"

[local]
"binaries/usr/bin" = "~/.local/bin"
"binaries/usr/local/share/zsh/site-functions" = "~/.local/zsh/site-functions"
"binaries/usr/share/man/man1" = "~/.local/man/man1"
"nvim" = "~/.config/nvim"
"misc/gitconfig" = "~/.config/gitconfig"
"misc/tmux.conf" = "~/.tmux.conf"
"misc/dracula" = "~/.local/tmux/dracula"
"zsh" = "~/.local/zsh/config"
